### ISSUE TITLE
Error found when configue step

### ISSUE THREAD

**Issue by hepingtao** [Werkov/PyQt4#2]
Qt Designer plugin disabled because Python library couldn't be found
An internal error occured.  Please report all the output from the program,
including the following traceback, to support@riverbankcomputing.com.
Traceback (most recent call last):
  File "configure.py", line 2294, in <module>
    main()
  File "configure.py", line 2279, in main
    subdirs=pyqt.qpy_libs() + pyqt_modules + xtra_modules + pyqt.tools(),
  File "configure.py", line 979, in tools
    link = "%s -lpython%d.%d%s" % (lib_dir_flag, py_major, py_minor, abi)
UnboundLocalError: local variable 'lib_dir_flag' referenced before assignment

**Comment by Werkov** [comment]
Hi hepingtao,
I'm afraid that I'm the only one who got notified about this issue. And since this is just an unofficial repo, I don't support it anyhow (I'm thus closing the issue). It seems you might have run into a bug in the configure script specific to the snapshotted version.

I suggest trying a newer version, bring up the question on StackOverflow or the authors of the PyQt4 directly.

Regards.
